# Версия docker-compose
version: '2'
# Список наших сервисов (контейнеров)
services:
    php:
        # у нас свой образ для PHP, указываем путь к нему и говорим что его надо собрать
        build: ./images/php
        # этот образ будет общаться с mysql
        links:
            - mysql
        # монтируем директорию с проектами
        volumes:
            - ./www:/var/www/html
            - ./hosts:/etc/apache2/sites-enabled
            - ./logs:/var/log/apache2
        # маршрутизируем порты
        ports:
            - "80:80"
        environment:
            APACHE_LOG_DIR: /var/log/apache2
    mysql:
        image: mysql:8
        ports:
            - "3306:3306"
        volumes:
            - ./mysql:/var/lib/mysql
        # задаем пароль для root пользователя
        environment:
            MYSQL_ROOT_PASSWORD: 1234
    phpmyadmin:
        image: 'phpmyadmin/phpmyadmin'
        restart: always
        ports:
           - '8080:80'
        links:
            - mysql
        environment:
            MYSQL_USERNAME: root
            MYSQL_ROOT_PASSWORD: 1234
            PMA_HOST: mysql