version: '2'
services:
    php:
        build: ./images/php
        volumes:
            - ./www:/var/www/html
            - ./hosts:/etc/apache2/sites-enabled
            - ./logs:/var/log/apache2
        ports:
            - "80:80"
            - "9001:9001"
        expose:
            - "9000"
        environment:
            APACHE_LOG_DIR: /var/log/apache2
            XDEBUG_CONFIG: "remote_host=172.17.0.1"
            PHP_IDE_CONFIG: "serverName=yii2.local"
    node:
        build: ./images/nodejs
        environment:
          - NODE_ENV=development
        volumes:
          - ./www/angular.local:/usr/src/app
        ports:
          - "3000:3000"
          - "4200:4200"
        command: "node /usr/src/app/index.js"
    mysql:
        image: mysql:5
        ports:
            - "3306:3306"            
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: 1234
    maria:
        image: mariadb:10
        ports:
            - "3307:3306"            
        volumes:
            - ./mariadb:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: 1234
    percona:
        image: percona:5
        ports:
            - "3308:3306"            
        volumes:
            - ./percona:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: 1234
    sphinx:
        build: ./images/sphinxsearch
        depends_on:
            - mysql
        ports:
            - "9306:9306"
        volumes:
            - ./sphinxsearch/config:/etc/sphinxsearch
            - ./sphinxsearch/data:/var/lib/sphinxsearch/data
            - ./sphinxsearch/log:/var/log/sphinxsearch
    phpmyadmin:
        image: 'phpmyadmin/phpmyadmin'
        restart: always
        ports:
           - '8081:80'
        environment:
            MYSQL_USERNAME: root
            MYSQL_ROOT_PASSWORD: 1234
            PMA_HOST: percona