# Для начала указываем исходный образ, он будет использован как основа
FROM node:8
# Необязательная строка с указанием автора образа
MAINTAINER eshaft <eshaft@gmail.com>

RUN npm install -g typescript \
	&& npm install --unsafe-perm -g @angular/cli